config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #仮のルーティング
  root 'items#index'
  resources :items do
    collection{ get "search"}
    collection do
      get 'items/get_category_children', defaults: { format: 'json' }
      get 'items/get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
  end

  resources :signup, only: [:crate] do
    collection do
      get  'index'
      get  'registration'
      get  'registration_omniauth'
      get  'phone'
      post 'phone' => 'signup#send_sms'
      get  'phone2'
      post 'phone2' => 'signup#check_sms'
      get  'address'
      get  'payment'
      post 'create'
      get  'complete'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :users, only: [:show, :edit] do
    collection do
      get 'login', to: 'users#login'
      get 'logout', to: 'users#logout'
      get 'card', to: 'users#card'
      get 'exhibiting', to: 'users#exhibiting'
    end
  end
  resources :personals

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  require 'payjp'
  require 'twilio-ruby'

  # ---------------
  # ログイン方法選択画面
  # ---------------
  def index
  end

  # ---------------
  # 会員情報入力画面
  # ---------------
  def registration
    # 新規インスタンスを作成する
    # user_paramsでpersonalモデルの項目も取得できるようにする
    @user = User.new
    @user.build_personal
  end

  # facebook、googleアカウント用
  def registration_omniauth
    # 新規インスタンスを作成する
    # user_paramsでpersonalモデルの項目も取得できるようにする
    @user = User.new(
      nickname:              session[:omniauth_nickname],
      email:                 session[:omniauth_email]
    )
    @user.build_personal
  end

  # ---------------
  # 電話番号の確認画面
  # ---------------
  def phone
    # 会員情報入力画面で入力された値をsessionに保存する
    session[:nickname]              = user_params[:nickname]
    session[:email]                 = user_params[:email]
    session[:password]              = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name]             = user_params[:personal_attributes][:last_name]
    session[:first_name]            = user_params[:personal_attributes][:first_name]
    session[:last_name_kana]        = user_params[:personal_attributes][:last_name_kana]
    session[:first_name_kana]       = user_params[:personal_attributes][:first_name_kana]
    session[:birthday]              = user_birthday_join
    
    if session[:omniauth_password]
      session[:password]              = session[:omniauth_password]
    end

    # usersテーブル登録準備
    # 新規インスタンスを作成し、sessionに保存された値を格納する
    @user = User.new(
      nickname:              session[:nickname],
      email:                 session[:email],
      password:              session[:password],
      profile:"",
      point: 0,
      provider:              session[:omniauth_provider],
      uid:                   session[:omniauth_uid]
    )

    # usersテーブル登録処理実行
    unless @user.valid?
      @user.build_personal
      unless session[:omniauth_password]
        render '/signup/registration'
        return
      end
      render '/signup/registration_omniauth'
      return
    end

    # 登録成功時：ユーザーIDをsessionに保存し、未ログインの場合ログインする
    # 登録失敗時：会員情報入力画面を表示する
    if @user.save!
      session[:user_id] = @user.id
      sign_in User.find(session[:user_id]) unless user_signed_in?
    else
      @user.build_personal
      render '/signup/registration'
      return
    end

    # personalsテーブル登録準備
    # 新規インスタンスを作成し、sessionに保存された値を格納する
    @personal = Personal.new(
      user_id:               session[:user_id],
      last_name:             session[:last_name],
      first_name:            session[:first_name],
      last_name_kana:        session[:last_name_kana],
      first_name_kana:       session[:first_name_kana],
      birthday:              session[:birthday]
    )

    # personalsテーブル登録処理実行
    # 登録失敗時：会員情報入力画面を表示する
    unless @personal.valid?
      @user.build_personal
      render '/signup/registration'
      return
    end

    unless @personal.save!
      @user.build_personal
      render '/signup/registration'
      return
    end

    # 電話番号の確認画面を表示する
    # 新規インスタンスを作成する
    @phone = Phone.new
  end

  # ---------------
  # SMS送信処理
  # ---------------
  def send_sms
    # 電話番号の確認画面で入力された値をsessionに保存する
    session[:phone_number] = phone_params[:phone_number]

    # 新規インスタンスを作成し、sessionに保存された値を格納する
    @phone = Phone.new(
      user_id:      session[:user_id],
      phone_number: session[:phone_number]
    )

    # 入力値チェック
    # 登録失敗時：電話番号の確認画面を表示する
    unless @phone.valid?
      render '/signup/phone'
      return
    end

    # SMS送信処理
    if phone_params[:phone_number].present?
      # 電話番号が取得できた場合
      # 取得した電話番号を+81にフォーマット
      phone_number = PhonyRails.normalize_number phone_params[:phone_number], country_code:'JP'
      # 認証番号（ランダムな4桁の整数）を生成し、sessionに格納する
      session[:secure_code] = rand(1000..9999)

      # SMS送信を行うための設定
      client = Twilio::REST::Client.new(ENV["TWILIO_ACCOUNT_SID"],ENV["TWILIO_AUTH_TOKEN"])

      # 送信処理実行
      begin
        # 送信元、送信先、メッセージ文を設定し送信する
        client.messages.create(
          from: ENV["TWILIO_NUMBER"],
          to:   phone_number,
          body: "#{session[:secure_code]}"
        )
      rescue
        # 送信失敗時
        # 電話番号の確認画面を表示する
        redirect_to phone_signup_index_path
        return false
      end
      # 送信成功時
      # 電話番号認証画面を表示する
      redirect_to phone2_signup_index_path
    else
      # 電話番号が取得できなかった場合
      # 電話番号の確認画面を表示する
      redirect_to phone_signup_index_path
    end
  end
  
  # ---------------
  # 電話番号認証画面
  # ---------------
  def phone2
    # 新規インスタンスを作成
    @authentication = SmsAuthenticationForm.new
  end

  # ---------------
  # 認証番号確認処理
  # ---------------
  def check_sms
    if params[:sms_authentication_form][:secure_code].present?
      if session[:secure_code] === params[:sms_authentication_form][:secure_code].to_i
        # 生成された認証番号と入力された認証番号が一致した場合
        # phonesテーブル登録準備
        # 新規インスタンスを作成し、sessionに保存された値を格納する
        @phone = Phone.new(
          user_id:      session[:user_id],
          phone_number: session[:phone_number]
        )
        # phonesテーブル登録処理実行
        if @phone.save!
          # 登録成功時：発送先・お届け先住所入力画面を表示する
          redirect_to address_signup_index_path
        else
          # 登録失敗時：電話番号認証画面を表示する
          render '/signup/phone2'
        end
      else
        # 生成された認証番号と入力された認証番号が一致しなかった場合
        # 電話番号認証画面を表示する
        redirect_to phone2_signup_index_path
      end
    else
      # 認証番号が取得出来なかった場合
      # 電話番号認証画面を表示する
      redirect_to phone2_signup_index_path
    end
  end

  # ---------------
  # 発送先・お届け先住所入力画面
  # ---------------
  def address
    # 新規インスタンスを作成する
    @address = Address.new
  end

  # ---------------
  #  支払い方法画面
  # ---------------
  def payment
    # 発送先・お届け先住所入力画面で入力された値をsessionに保存する
    session[:address_last_name]        = address_params[:last_name]
    session[:address_first_name]       = address_params[:first_name]
    session[:address_last_name_kana]   = address_params[:last_name_kana]
    session[:address_first_name_kana]  = address_params[:first_name_kana]
    session[:postcode]                 = address_params[:postcode]
    session[:prefecture_id]            = address_params[:prefecture_id]
    session[:city]                     = address_params[:city]
    session[:address]                  = address_params[:address]
    session[:building]                 = address_params[:building]
    session[:phone_number_sub]         = address_params[:phone_number_sub]

    # addressesテーブル登録準備
    # 新規インスタンスを作成し、sessionに保存された値を格納する
    @address = Address.new(
      user_id:               session[:user_id],
      last_name:             session[:address_last_name], 
      first_name:            session[:address_first_name], 
      last_name_kana:        session[:address_last_name_kana], 
      first_name_kana:       session[:address_first_name_kana], 
      postcode:              session[:postcode],
      prefecture_id:         session[:prefecture_id],
      city:                  session[:city],
      address:               session[:address],
      building:              session[:building],
      phone_number_sub:      session[:phone_number_sub]
    )

    # addressesテーブル登録処理実行
    # 登録失敗時：発送先・お届け先住所入力画面を表示する
    unless @address.valid?
      render '/signup/address'
      return
    end

    unless @address.save!
      render '/signup/address'
      return
    end

    # 支払い方法画面を表示する（card_controllerのnewアクションを実行する）
    redirect_to new_card_path
  end

  # ---------------
  #  登録完了画面
  # ---------------
  def complete
  end


  private

  # userモデルのparams
  def user_params
    params.require(:user).permit(
      :nickname, 
      :email, 
      :password, 
      :password_confirmation,
      personal_attributes:[:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday]
    )
  end

  # phoneモデルのparams
  def phone_params
    params.require(:phone).permit(
      :phone_number
    )
  end

  # addressモデルのparams
  def address_params
    params.require(:address).permit(
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postcode,
      :prefecture_id,
      :city,
      :address,
      :building,
      :phone_number_sub
    )
  end

  # 分割されている生年月日を結合する
  def user_birthday_join
    date = params[:birthday]

    if date['birthday(1i)'].empty? && date['birthday(2i)'].empty? && date['birthday(3i)'].empty?
      return
    else
      birthday = Date.new(
        date['birthday(1i)'].to_i,
        date['birthday(2i)'].to_i,
        date['birthday(3i)'].to_i)
    end
  end
end

app/views/signup/address.html.haml
.common-container
  .common-header
    %h1
      //発送元・お届け先住所入力画面のヘッダー
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'
    -# active_redは赤丸表示、afterはactiveより後（右側）の線を定義、beforeはactiveより前（左側）
    -# thoughはすでに入力完了したページ部分、赤丸表示とactive_redまでの横線を赤く表示
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.through
          電話番号認証
          .progress-status
        %li.active_red
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.l-step3-container.clearfix
    .l-step3-content
      %section.l-chapter-container
        %h2.l-chapter-head
          発送元・お届け先住所入力
        = form_for @address, url: payment_signup_index_path, method: :get, html: {class: "l-step3-inner registration-form"} do |f|
          .l-step3-inner
            %input{type: "hidden", name: "csrf_value", value: ""}
          .l-step3-content
            .form-group
              %label お名前
              %span.contents__form__require 必須
              = f.text_field :last_name, placeholder: "例）山田", class: "input-default"
              = f.text_field :first_name, placeholder: "例）彩", class: "input-default"
              - if @address.errors.messages[:last_name].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:last_name).each do |message|
                    %li= message
              - if @address.errors.messages[:first_name].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:first_name).each do |message|
                    %li= message
            .form-group
              %label お名前カナ
              %span.contents__form__require 必須
              = f.text_field :last_name_kana, placeholder: "例）ヤマダ", class: "input-default"
              = f.text_field :first_name_kana, placeholder: "例）アヤ", class: "input-default"
              - if @address.errors.messages[:last_name_kana].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:last_name_kana).each do |message|
                    %li= message
              - if @address.errors.messages[:first_name_kana].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:firstfirst_name_kana_name).each do |message|
                    %li= message
            .form-group
              %label 郵便番号
              %span.contents__form__require 必須
              =f.text_field :postcode, placeholder:"例) 123-4567", maxlength:"8", class: "input-default"
              - if @address.errors.messages[:postcode].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:postcode).each do |message|
                    %li= message
            .form-group
              %label 都道府県
              %span.contents__form__require 必須
              .select-wrap
                = fa_icon "arrow-bottom"
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--",class: "select-default"
                - if @address.errors.messages[:prefecture_id].any?
                  %ul.contents__errors__message
                    - @address.errors.full_messages_for(:prefecture_id).each do |message|
                      %li= message
            .form-group
              %label 市区町村
              %span.contents__form__require 必須
              = f.text_field :city, placeholder: "例）横浜市緑区", class: "input-default"
              - if @address.errors.messages[:city].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:city).each do |message|
                    %li= message
            .form-group
              %label 番地
              %span.contents__form__require 必須
              = f.text_field :address, placeholder: "例）青山1-1-1", class: "input-default"
              - if @address.errors.messages[:address].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:address).each do |message|
                    %li= message
            .form-group
              %label 建物名
              %span.contents__form__arbitrary 任意
              = f.text_field :building, placeholder: "例) 柳ビル103", class: "input-default"
              - if @address.errors.messages[:building].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:building).each do |message|
                    %li= message
            .form-group
              %label 電話
              %span.contents__form__arbitrary 任意
              = f.text_field :phone_number_sub, placeholder:"例) 09012345678", class: "input-default"
              - if @address.errors.messages[:phone_number_sub].any?
                %ul.contents__errors__message
                  - @address.errors.full_messages_for(:phone_number_sub).each do |message|
                    %li= message
            %input{type: "hidden", name: ""}
            %button{type: "submit", class: "btn-default btn-red"}
              次へ進む
  = render  "shared/signup-footer"

app/views/signup/complete.html.haml
.common-container
  .common-header
    %h1
      //会員登録完了画面のヘッダー
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'
    -# active_redは赤丸表示、afterはactiveより後（右側）の線を定義、beforeはactiveより前（左側）
    -# thoughはすでに入力完了したページ部分、赤丸表示とactive_redまでの横線を赤く表示
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.through
          電話番号認証
          .progress-status
        %li.through
          お届け先住所入力
          .progress-status
        %li.through
          支払い方法
          .progress-status
        %li.active_red
          完了
          .progress-status
  %main.step5-main
    %section.l-step5-container
      %h2.l-chapter-head.registraition
        会員登録完了
      .l-step5-inner.registration-form
        .l-step5-content
          %p 
            ありがとうございます。
            %br 
            会員登録が完了しました。
          =link_to root_path(), class: "btn-default btn-red" do
            .start-btn メルカリをはじめる
      = link_to "#" do
        %img{class:"step5-banner-sp",src:"//www-mercari-jp.akamaized.net/assets/img/signup/jp/banner-sp.jpg?2651893653"}
      = link_to "#" do
        %img{class:"step5-banner-pc",src:"//www-mercari-jp.akamaized.net/assets/img/signup/jp/banner-pc.jpg?2651893653"}
  = render "shared/signup-footer"

app/views/signup/index.html.haml
-# ページのヘッダー部分
.common-container
  = render "shared/signup-header"
  -# 登録方法選択画面
  %main.contents-main
    %section.contents-container
      %h2.contents-head
        新規会員登録
      .contents.registration-form
        .contents-select
          = link_to registration_signup_index_path ,class:"contents__btn mail-address" do
            = fa_icon 'envelope'
            メールアドレスで登録する
          = link_to user_facebook_omniauth_authorize_path, method: :post, class: "contents__btn facebook" do
            = fa_icon 'facebook-square'
            Facebookで登録する
          = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "contents__btn google" do
            = image_tag "googlelogo.png"
            Googleで登録する
    -# ページのフッダー部分
  = render 'shared/signup-footer'

app/views/signup/payment.html.haml
.common-container
  .common-header
    %h1
      //支払い方法入力画面のヘッダー
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'
    -# active_redは赤丸表示、afterはactiveより後（右側）の線を定義、beforeはactiveより前（左側）
    - # thoughはすでに入力完了したページ部分、赤丸表示とactive_redまでの横線を赤く表示
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.through
          電話番号認証
          .progress-status
        %li.through
          お届け先住所入力
          .progress-status
        %li.active_red
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.l-step4-container.clearfix
    .l-step4-content
      %section.l-chapter-container
        %h2.l-chapter-head
          支払い方法
        -# = form_for "", url: "", method: :get, html: {class: 'l-step4-inner registration-form'} do |f|
        -# = form_tag(complete_signup_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        = form_tag(complete_signup_index_path, method: :get, html: {class: 'l-step4-inner registration-form'}, id: 'charge-form', name: "inputForm") do
          .l-step4-inner
            %input{type: "hidden", name: "csrf_value", value: ""}
          .l-step4-content
            .form-group
              %label カード番号
              %span.contents__form__require 必須
              -# %input{type: "text", id:"payment_card_no", placeholder:"半角数字のみ", maxlength:"19",class: "input-default"}
              = text_field_tag "number", "", class: "number input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %ul{id:"card-no-error-wrapper",class:"has-error-text"}
              %ul.signup-card-list
                %li
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?465897195", width:"49", height:"20"}
                %li  
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?465897195", width:"34", height:"20"}
                %li
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?465897195", width:"30", height:"20"}
                %li
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?465897195", width:"32", height:"20"}
                %li
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?465897195", width:"21", height:"20"}
                %li
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?465897195", width:"32", height:"20"}
                %li
                  %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?465897195", width:"32", height:"20"}
            .form-group.signup-form-expire
              %label 有効期限
              %span.contents__form__require 必須
              %br
              .select-wrap.half
                -# %select{id:"payment_card_expire_mm",class:"select-default"}
                %select#exp_month{name: "exp_month", type: "text", class:"select-default"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                = fa_icon "icon-arrow-bottom"
                %span 月
              .select-wrap.half
                -# %select{id:"payment_card_expire_yy",class:"select-default"}
                %select#exp_year{name: "exp_year", type: "text", class:"select-default"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                = fa_icon "icon-arrow-bottom"
                %span 年
                -# %ul{id:"expire-mm-error-wrapper",class:"has-error-text"}
                -# %ul{id:"expire-yy-error-wrapper",class:"has-error-text"}
                %ul{id:"exp_month",class:"has-error-text"}
                %ul{id:"exp_year",class:"has-error-text"}
            .form-group
              %label セキュリティコード
              %span.contents__form__require 必須
              -# %input{type: "text", id:"payment_card_security_code", placeholder:"カード背面4桁もしくは3桁の番号",class: "input-default"}
              = text_field_tag "cvc", "", class: "cvc input-default", placeholder:"カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
              %ul{id:"security-code-error-wrapper",class:"has-error-text"}
              .signup-seqcode
                .signup-seqcode-text
                  %span.form-question ? 
                  カード裏面の番号とは？
                  -# jsでテキストをクリックした時にイメージが発火するようにする場所
                .signup-seqcode-info
                -# jsでテキストをクリックした時にイメージが発火するようにする場所
                  -# カードの裏面をご参照ください。
                  -# %br
                    -# %img{src:"//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?465897195"}
            %input{type: "hidden", name:"user_id", id:"user_id"}
            %input{type: "hidden", name:"encrypted_card_data", id:"encrypted_card_data"}
            %p{id:"primary-error",class:"has-error-text"}
            %input{type: "hidden", name:"after_save_callback"}
            -# %button{type: "submit", class: "btn-default btn-red"}
              次へ進む
            = submit_tag "次へ進む", id: "token_submit", class: "btn-default btn-red"
  = render  "shared/signup-footer"

app/views/signup/phone.html.haml
.common-container
  .common-header
    %h1
      //電話確認と電話認証画面のヘッダー
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'
    -# active_redは赤丸表示、afterはactiveより後（右側）の線を定義、beforeはactiveより前（左側）
    -# thoughはすでに入力完了したページ部分、赤丸表示とactive_redまでの横線を赤く表示
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.active_red
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.step2-main
    %section.l-step2-container
      %h2.l-chapter-head.registration
        電話番号の確認
      = form_for @phone, url: phone_signup_index_path, method: :post, html: {class: "l-step2-inner registration-form", novalidate: "novalidate"} do |f|
        .l-step2-content
          .form-group
            %label{for: "phone_number"}
              携帯電話の番号
            = f.text_field :phone_number, placeholder: "携帯電話の番号を入力", class: "input-default"
            - if @phone.errors.messages[:phone_number].any?
              %ul.contents__errors__message
                - @phone.errors.full_messages_for(:phone_number).each do |message|
                  %li= message
          %p
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = f.submit "SMSを送信する", class: "btn-default btn-red"
          %p
            ※携帯電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .form-group.text-right
            = link_to '', target: '_blank' do
              電話番号の確認が必要な理由
              =fa_icon "chevron-right"

  = render 'shared/signup-footer'

app/views/signup/phone2.html.haml
.common-container
  .common-header
    %h1
      //電話確認と電話認証画面のヘッダー
      = link_to "#" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'
    -# active_redは赤丸表示、afterはactiveより後（右側）の線を定義、beforeはactiveより前（左側）
    -# thoughはすでに入力完了したページ部分、赤丸表示とactive_redまでの横線を赤く表示
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.through
          会員情報
          .progress-status
        %li.active_red
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.step2-main
    %section.l-step2-container
      %h2.l-chapter-head.registration
        電話番号認証
      = form_for @authentication, url: phone2_signup_index_path, method: :post, html: {class: "l-step2-inner registration-form", novalidate: "novalidate"} do |f|
        .l-step2-content
          .form-group
            %label{for: "captcha"}
              認証番号
            = f.text_field :secure_code, placeholder: "認証番号を入力", class: "input-default"
          %p
            SMSで届いた認証番号を入力してください
          = f.submit "認証して完了", class: "btn-default btn-red"
        %input{type: "hidden", name: "csrf_value", value: ""}
      %form{action: "", method: "POST", class: "l-step2-inner registration-form", novalidate: "novalidate"}
        %input{type: "hidden", name:"after_save_callback", value: ""}
        .l-step2-content
          %h3.l-chapter-sub-head
            30秒たっても認証番号が届かない方へ
          %p.l-step2-text
            電話で認証番号を聞くこともできます。
          %button{type: "submit", class: "btn-default btn-red"}
            電話で認証番号を聞く（通話無料）
        %input{type: "hidden", name: "csrf_value", value: ""}
        %input{type: "hidden", name: "id", value: ""}
      .l-step2-inner.registration-form
        .l-step2-content
          %h3.l-chapter-sub-head
            認証番号を再送することもできます。もう一度電話番号を入力して下さい。
          %p
            = link_to "電話番号を再度入力する"
          %p
            ※SMSが届かない場合は
            = link_to "SMS受信設定"
            を確認して、もう一度電話番号を入力してください。
  = render 'shared/signup-footer'