config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #仮のルーティング
  root 'items#index'
  resources :items do
    collection{ get "search"}
    collection do
      get 'items/get_category_children', defaults: { format: 'json' }
      get 'items/get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
  end

  resources :signup, only: [:crate] do
    collection do
      get  'index'
      get  'registration'
      get  'registration_omniauth'
      get  'phone'
      post 'phone' => 'signup#send_sms'
      get  'phone2'
      post 'phone2' => 'signup#check_sms'
      get  'address'
      get  'payment'
      post 'create'
      get  'complete'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :users, only: [:show, :edit] do
    collection do
      get 'login', to: 'users#login'
      get 'logout', to: 'users#logout'
      get 'card', to: 'users#card'
      get 'exhibiting', to: 'users#exhibiting'
    end
  end
  resources :personals

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  # 買った商品、現在売っている商品、すでに売れた商品の条件付きアソシエーション
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, -> { where("buyer_id is NULL") }, foreign_key: "saler_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "saler_id", class_name: "Item"

  belongs_to :prefecture
  has_many :evaluations
  has_many :cards

  has_one :personal
  accepts_nested_attributes_for :personal
  
  belongs_to :phone
  has_one :address
  accepts_nested_attributes_for :address

  # フォーマット定義
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # registration入力項目
  validates :nickname, presence: true, length:{ maximum: 10 }
  validates :email, presence: true, length:{ maximum: 254 }, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length:{ minimum: 7, maximum: 128 }
  validates :provider, length:{ in: 8..13 }, allow_blank: true
  validates :uid, length:{ in: 15..21}, allow_blank: true

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(access_token)
    data = access_token.info

    # access_tokenのemailがusersテーブルに登録済みか確認する
    user = User.where(email: data['email']).first

    unless user
      # access_tokenのrmailが登録されていない場合
      # ソーシャルアカウントから取得したneme、email、passwordをuser変数に格納する
      user = User.new(
        nickname: data['name'],
        email: data['email'],
        password: Devise.friendly_token[0,20],
        provider: access_token.provider,
        uid: access_token.uid
      )
    end
    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  # Facebookアカウントによる認証
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      # 認証画面で選択したアカウントのemailが登録済みだった場合ログインする
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Facebook'
      sign_in_and_redirect @user, event: :authentication
    else
      # 認証画面から取得したデータをセッションに格納する
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) 
      session[:omniauth_nickname]     = @user.nickname
      session[:omniauth_email]        = @user.email
      session[:omniauth_password]     = @user.password
      session[:omniauth_provider]     = @user.provider
      session[:omniauth_uid]          = @user.uid

      # 会員情報入力画面（facebook、googleアカウント用）へ遷移する
      redirect_to registration_omniauth_signup_index_path, alert: @user.errors.full_messages.join("\n")
    end
  end

  # googleアカウントによる認証
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      # 認証画面で選択したアカウントのemailが登録済みだった場合ログインする
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      # 認証画面から取得したデータをセッションに格納する
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      session[:omniauth_nickname]   = @user.nickname
      session[:omniauth_email]      = @user.email
      session[:omniauth_password]   = @user.password
      session[:omniauth_provider]   = @user.provider
      session[:omniauth_uid]        = @user.uid

      # 会員情報入力画面（facebook、googleアカウント用）へ遷移する
      redirect_to registration_omniauth_signup_index_path, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def create
    # reCAPTCHAのバリデーション
    if verify_recaptcha
      super
    else
      self.resource = resource_class.new
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_search

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def login
  end

  def logout
    
  end

  def card
  end

  def exhibiting
    @user = User.find(current_user.id)
    @items = Item.where(saler_id: @user.id).order("id DESC").limit(15)
  end


  private

  def set_search
    @q = Item.search(params[:q])
  end
end

app/views/users/_side_menu.html.haml
// マイページ・プロフィール編集画面・本人確認画面・ログアウト画面・クレジットカード登録画面で使用
.l-side-menu
  %nav.mypage__nav
    %ul.mypage__nav-list
      %li
        = link_to user_path(id: current_user.id), class: "mypage__nav-list-item active" do
          マイページ
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          お知らせ
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          やることリスト
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          いいね！一覧
          = fa_icon "chevron-right"
      %li
        = link_to new_item_path, class: "mypage__nav-list-item" do
          出品する
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          出品した商品-出品中
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          出品した商品-取引中
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          出品した商品-売却済み
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          購入した商品-取引中
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          購入した商品-過去の取引
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          ニュース一覧
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          評価一覧
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          ガイド
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          お問い合わせ
          = fa_icon "chevron-right"
    %h3.mypage__nav-title
      メルペイ
    %ul.mypage__nav-list
      %li
        = link_to '', class: "mypage__nav-list-item" do
          売上・振込申請
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          ポイント
          = fa_icon "chevron-right"
    %h3.mypage__nav-title
      設定
    %ul.mypage__nav-list
      %li
        = link_to '', class: "mypage__nav-list-item" do
          プロフィール
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          発送・お届け先住所変更
          = fa_icon "chevron-right"
      %li
        = link_to '/users/card', class: "mypage__nav-list-item" do
          支払い方法
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          メール/パスワード
          = fa_icon "chevron-right"
      %li
        = link_to edit_personal_path(@user, id: current_user.id), class: "mypage__nav-list-item" do
          本人情報
          = fa_icon "chevron-right"
      %li
        = link_to '', class: "mypage__nav-list-item" do
          電話番号の確認
          = fa_icon "chevron-right"
      %li
        = link_to logout_users_path, class: "mypage__nav-list-item" do
          ログアウト
          = fa_icon "chevron-right"

app/views/users/card.html.haml
//クレジットカード登録画面
.user-container
  // ヘッダーの部分テンプレートを挿入
  = render partial: "shared/main_header"
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      - breadcrumb :card
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"
  %main.l-container.clearfix
    .l-content
      %section.l-chapter-container
        %h2.l-chapter__head
          支払い方法
        .l-single-inner
          %section
            .l-single-content
              %h3.l-chapter-sub-head
                クレジットカード一覧
            %ul.setting-payment-list
              // この中に登録しているクレジットカードの一覧を表示
          %section.setting-add-card
            .l-single-content
              = link_to new_card_path, class: "btn-default btn-red submit-btn" do
                = fa_icon "credit-card"
                クレジットカードを追加する
          .setting-not-regist
            = link_to "", target: "blank" do
              %span
                支払い方法について
              = fa_icon "chevron-right"
    // 部分テンプレートのサイドメニューを呼び出し
    = render partial: "side_menu"

  //バナーのテンプレートを挿入
  = render partial: "shared/main_aside"
  //フッターのテンプレートを挿入
  = render partial: "shared/main_footer"
  //出品ボタンのテンプレート呼びだし
  = render partial: "shared/sell_btn"

app/views/users/edit.html.haml
-# プロフィール編集画面
.user-container
  = render partial: 'shared/main_header'
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      - breadcrumb :edit
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"
  .l-container.cleafix
    .l-content
      %section.l-chapter-container
        %h2.l-chapter-head プロフィール
        %form{:action => "", :method => "POST"}
          %input{:name => "__csrf_value", :type => "hidden", :value => "0ee9b933761fd5cc41065da1969d19cf8f2f85ed4f18225a01dc05f4081f9bb50b4244aa1ee100f87c5fc97bcdb6608de83a2e62f3fa088af8052d42a2504583d", class: "input-default"}/
          .setting-profile-icon
            %figure
              %img{:height => "60", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "60"}/
            %input{:name => "nickname", :placeholder => "例)AYA☆セール中", :type => "text", :value => "",  class: "input-default"}/
          .setting-profile-content
            %textarea.textarea-default{:name => "introduction", :placeholder => "例）こんにちは"}
            %button{:type => "submit", class: "btn-default btn-red"} 変更する

    = render partial: "side_menu"  

  //バナーのテンプレートを挿入
  = render partial: "shared/main_aside"
  //フッターのテンプレートを挿入
  = render partial: "shared/main_footer"
  //出品ボタンのテンプレート呼びだし
  = render partial: "shared/sell_btn"

app/views/users/exhibiting.html.haml
.user-container
  = render partial: 'shared/main_header'
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      - breadcrumb :exhibiting
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"

  .l-container.cleafix
    .l-content
      %section.l-chapter-container
        %h2.l-chapter-head 出品した商品
        .exhibiting_box
          .exhibiting_box__status
            .exhibiting_box__status--1
              出品中
            .exhibiting_box__status--2
              取引中
            .exhibiting_box__status--3
              売却済み
          .exhibiting_box-item
            - @items.each do |item|
              = link_to item_path(item) do
                .exhibiting_box-item__myexhibiting
                  .exhibiting_box-item__myexhibiting--image
                    .exhibiting-image
                      = image_tag item.photos.first.photo, style: "width: 50px; height: 50px;"
                  .exhibiting_box-item__myexhibiting--detail
                    .exhibiting-name
                      = item.name
          
    = render partial: "side_menu"

  //バナーのテンプレートを挿入
= render partial: "shared/main_aside"
//フッターのテンプレートを挿入
= render partial: "shared/main_footer"
//出品ボタンのテンプレート呼びだし
= render partial: "shared/sell_btn"

app/views/users/login.html.haml
.common-container
  = render 'shared/signup-header'
  %main.login-main
    .login-panel
      .login-no-account
        %p
          アカウントをお持ちでない方はこちら
        = link_to "新規会員登録"
      .login-form-inner
        = link_to user_facebook_omniauth_authorize_path, method: :post, class: "btn-default btn-sns btn-sns-facebook" do
          = fa_icon "facebook-square"
          Facebookでログイン
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post, id: "google-login", class: "btn-default btn-sns btn-sns-google" do
          = image_tag "googlelogo.png"
          Googleでログイン
      = form_for(resource, as: resource_name, url: user_session_path, method: :post, novalidate: "novalidate") do |f|
        .login-form-inner
          .form-group
            = f.email_field :email, value: "", placeholder: "メールアドレス", class: "login-input-text input-default"
          .form-group
            = f.password_field :password, placeholder: "パスワード", class: "login-input-text input-default"
          .form-group
            = recaptcha_tags
                  
          = f.submit "ログイン", class: "login-submit btn-default btn-red"
          =link_to "パスワードをお忘れの方"
    -# ページのフッダー部分
  = render 'shared/signup-footer'

app/views/users/logout.html.haml
//ユーザーログアウトページ
.user-container
  = render partial: "shared/main_header"
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      - breadcrumb :logout
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"    
  %main.l-container.clearfix
    .l-content
      .l-chapter-container
        %form{action: "", method: "POST", class: "l-single-inner", novalidate: "novalidate"}
          .l-single-content
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default btn-red"

    // 部分テンプレートのサイドメニューを呼び出し
    = render partial: "side_menu"
    


  //バナーのテンプレートを挿入
  = render partial: "shared/main_aside"
  //フッターのテンプレートを挿入
  = render partial: "shared/main_footer"
  //出品ボタンのテンプレート呼びだし
  = render partial: "shared/sell_btn"

app/views/users/show.html.haml
//ユーザーマイページ
.user-container
  = render partial: "shared/main_header"
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      -# config/breadcrumbs.rbに定義したshowを呼び出し
      - breadcrumb :show
      -# 下記を記述した箇所にパンくずリストを表示させる。
      -# separatorはパンくずの間の区切り「&rsaquo」は出力されると「›」になる。
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"
  %main.l-container.clearfix
    .l-content
      %section.mypage__user-iconbox
        = link_to '' do
          %figure
            = image_tag 'mrkr-icon.png', size: "60x60"
          %h2.crrent-user__name.bold
            testuser
          .current-user__numbers
            .current-user__evaluation
              評価
              %span.bold
                5
            .current-user__items
              出品数
              %span.bold
                10

      %section.mypage__informations
        %ul.mypage__informations__tab
          // タブが切り替わるようになっており、jsで参照したいコンテンツにactiveクラスを付与する。
          %li.active
            %h3
              = link_to 'お知らせ'
          %li
            %h3
              = link_to 'やることリスト'
        .mypage__tab-content
          %ul#mypage__tab-notification.mypage__list.tab-pane.active
            %li
              = link_to do
                %figure
                  = image_tag 'mercari_profile.png', size: "48x48"
                .mypage__list__body
                  .mypage__list__content
                    お知らせテストお知らせテストお知らせテストお知らせテストお知らせテストお知らせテストお知らせテスト
                  .mypage__list__time.time
                    = fa_icon "clock-o"
                    %span
                      2 時間前
                = fa_icon "chevron-right"
            %li
              = link_to do
                %figure
                  = image_tag 'mercari_profile.png', size: "48x48"
                .mypage__list__body
                  .mypage__list__content
                    テスト
                  .mypage__list__time.time
                    = fa_icon "clock-o"
                    %span
                      3 時間前
                = fa_icon "chevron-right"
            %li.mypage__go-list
              = link_to '一覧を見る'
          %ul#mypage__tab-todo.mypage__list.tab-pane
            // リストがある場合とない場合で分ける必要がある
            .mypage__list-not-found.bold
              =image_tag "mrkr-gray.png", size: "90x90"
              .mypage__list-not-found__text
                現在、やることリストはありません

      %section.mypage__transaction
        %h2.mypage__transaction__tab-head
          購入した商品
        %ul.mypage__transaction__tab
          //jsでactiveクラスを付与する
          %li.active
            %h3
              = link_to '取引中'
          %li
            %h3
              = link_to '過去の取引'
        .mypage__tab-content
          // タブが切り替わるようになっており、jsで参照したいコンテンツにactiveクラスを付与する。
          %ul#mypage__tab-trading.mypage__list.tab-pane.active
            // リストの有無で条件分岐
            .mypage__list-not-found.bold
              =image_tag "mrkr-gray.png", size: "90x90"
              .mypage__list-not-found__text
                取引中の商品がありません
          %ul#mypage__tab-traded.mypage__list.tab-pane
            // リストの有無で条件分岐
            %li
              = link_to do
                %figure
                  = image_tag 'mrkr-icon.png'
                .mypage__list__body
                  .mypage__list__content
                    「〇〇」を購入しました。
                    %span
                      取引が完了しました
                  .mypage__list__content__status.done.bold
                    取引完了
                = fa_icon "chevron-right"
            %li.mypage__go-list
              = link_to '一覧を見る'
    
    // 部分テンプレートのサイドメニューを呼び出し
    = render partial: "side_menu"


  //バナーのテンプレートを挿入
  = render partial: "shared/main_aside"
  //フッターのテンプレートを挿入
  = render partial: "shared/main_footer"
  //出品ボタンのテンプレート呼びだし
  = render partial: "shared/sell_btn"