config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #仮のルーティング
  root 'items#index'
  resources :items do
    collection{ get "search"}
    collection do
      get 'items/get_category_children', defaults: { format: 'json' }
      get 'items/get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
  end

  resources :signup, only: [:crate] do
    collection do
      get  'index'
      get  'registration'
      get  'registration_omniauth'
      get  'phone'
      post 'phone' => 'signup#send_sms'
      get  'phone2'
      post 'phone2' => 'signup#check_sms'
      get  'address'
      get  'payment'
      post 'create'
      get  'complete'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :users, only: [:show, :edit] do
    collection do
      get 'login', to: 'users#login'
      get 'logout', to: 'users#logout'
      get 'card', to: 'users#card'
      get 'exhibiting', to: 'users#exhibiting'
    end
  end
  resources :personals

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_main_aside.html.haml
.aside
  .aside-content
    = link_to "" do
      = image_tag "//web-jp-assets.mercdn.net/_next/static/images/mercari_icon-f75780e32e41e052c8aaa8b446331cd8.png"
      .aside-banner__link
        スマホでかんたんフリマアプリ
        .aside-banner__link__text
          今すぐ無料ダウンロード！
  .aside2-content
    .aside2-banner
      .aside2-banner__links
        .aside2-banner__links__text1
          スマホでかんたんフリマアプリ
        .aside2-banner__links__text2
          今すぐ無料ダウンロード！
        .aside2-banner__links__logo
          = image_tag "//web-jp-assets.mercdn.net/_next/static/images/mercari_icon-f75780e32e41e052c8aaa8b446331cd8.png"
          = link_to "#" do
            = image_tag "appstore.svg"
          = link_to "#" do
            = image_tag "googleplay.svg"
      .aside2-banner__figure
        = image_tag "mercari5.png"

app/views/shared/_main_footer.html.haml
%footer.main-footer
  %nav
    .merucari-overview.footer-top.footer-contents
      %h2.footer-contents__title
        メルカリについて
      %ul.footer-contents__lists
        %li.list
          = link_to "会社概要（運営会社)"
        %li.list
          = link_to "採用情報"
        %li.list
          = link_to "プレスリリース"
        %li.list
          = link_to "公式ブログ"
        %li.list
          = link_to "メルカリロゴ利用ガイドライン"
        = link_to "#", class:"merucari-overview__btn twitter" do
          = fa_icon 'twitter' 
        = link_to "#", class:"merucari-overview__btn facebook" do
          = fa_icon 'facebook-square'
    .merucari-guide.footer-top.footer-contents
      %h2.footer-contents__title
        ヘルプ＆ガイド
      %ul.footer-contents__lists
        %li.list
          = link_to "メルカリガイド"
        %li.list
          = link_to "らくらくメルカリ便"
        %li.list
          = link_to "ゆうゆうメルカリ便"
        %li.list
          = link_to "大型メルカリ便"
        %li.list
          = link_to "車体取引ガイド"
        %li.list
          = link_to "メルカリあんしん・あんぜん宣言！"
        %li.list
          = link_to "偽ブランド品撲滅への取り組み"
        %li.list
          = link_to "メルカリボックス"
    .merucari-privacy.footer-contents
      %h2.footer-contents__title
        プライバシーと利用規約
      .merucari-privacy__1
        %ul
          %li.list
            = link_to "プライバシーポリシー"
          %li.list
            = link_to "メルカリ利用規約"
          %li.list
            = link_to "あんしんスマホサポート制度に関する利用規約"
          %li.list
            = link_to "コンプライアンスポリシー"
      .merucari-privacy__2
        %ul
          %li.list
            = link_to "個人データの安全管理に係る基本方針"
          %li.list
            = link_to "特定商取引に関する表記"
          %li.list
            = link_to "資金決済法に基づく表示"
          %li.list
            = link_to "法令順守と犯罪抑止のために"
    .merucari-country.footer-contents
      %h2.merucari-country__title
        国
      %ul.merucari-country__lists
        %li.list
          = link_to "日本", "", class: "country-link"
          = link_to "United States", class: "country-link"
  .bottom-row
    = link_to root_path do
      %img{ class:"bottom-row__lists", src:"//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?2482339763" }
    %span.bottom-row__lists__name  @2019 Merucari

app/views/shared/_main_header.html.haml
.header
  .upper-row
    = link_to root_path do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari", class: 'mercari-icon'
    - if user_signed_in?
      //ログイン時
      .upper-row__user
        .user-information
          = link_to '#' do
            = fa_icon 'bell', class: 'icon'
        .user-information
          = link_to '#' do 
            = fa_icon 'check', class: 'icon'
        .user-information
          = link_to user_path(id: current_user.id), class: 'userpage-link' do
            = image_tag 'mrkr-icon.png', class: 'user-icon', size: '32x32'
    - else
      //未ログイン
      .upper-row__user
        = link_to '新規会員', '/signup/index',class: "upper-row__user__registration" 
        
        = link_to 'ログイン', '/users/login',class: "upper-row__user__login"
  
  .center-row__search
    = search_form_for @q, url: search_items_path do |f|
      = f.search_field :name_cont, class: "center-row__search--input", placeholder: "何をお探しですか？", style: "width: 100%; height: 40px;"
      = f.button :submit, class: "center-row__search--button" do
        = fa_icon 'search'
  %nav.under-row
    = link_to categories_path, class: "under-row__list" do
      = fa_icon 'list'
      %span
        カテゴリーから探す
    = link_to '#', class: "under-row__list" do
      = fa_icon 'tag'
      %span
        ブランドから探す

// 横に広がった時のヘッダー
.header-wide
  .header-wide__inner
    .upper-row
      .mercari-logo
        = link_to root_path do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari"
      = search_form_for @q, url: search_items_path do |f|
        = f.search_field :name_cont, class: "upper-row__search--input", placeholder: "何をお探しですか？", style: "width: 100%; height: 40px;"
        = f.button :submit, class: "upper-row__search--button" do
          = fa_icon 'search'
    .under-row
      .under-row__links
        .under-row__links__content
          = link_to categories_path do
            = fa_icon 'list'
            %span
              カテゴリーから探す
        .under-row__links__content
          = link_to '#' do
            = fa_icon 'tag'
            %span
              ブランドから探す

      - if user_signed_in?
        %ul.under-row__lists
          %li.list
            = link_to '#' do
              = fa_icon 'heart', class: 'icon'
              いいね！一覧
          %li.list
            = link_to '#' do
              = fa_icon 'bell', class: 'icon'
              お知らせ
          %li.list
            = link_to '#' do 
              = fa_icon 'check', class: 'icon'
              やることリスト
          %li.list
            = link_to user_path(id: current_user.id) do
              = image_tag 'mrkr-icon.png'
              マイページ
      - else
        // 未ログイン時
        .under-row__user
          .under-row__user__registration
            = link_to '/signup/index' do
              新規会員登録
          .under-row__user__login    
            = link_to '/users/login' do
              ログイン

app/views/shared/_sell_btn.html.haml
= link_to new_item_path, class: "footer-sell-btn" do
  %div 出品
  = fa_icon 'camera'

app/views/shared/_signup-footer.html.haml
.common-footer
  %nav
    %ul.common-footer-container
      %li.common-footer-container__list
        = link_to "プライバシーポリシー"
      %li.common-footer-container__list
        = link_to "メルカリ利用規約"
      %li.common-footer-container__list
        = link_to "特定商取引に関する表記"
  = link_to root_path do
    = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?1248199994', alt: "mercari-logo-gray" , class: 'common-footer-container__logo'   
  %p
    %small©︎2019 Mercari

app/views/shared/_signup-header.html.haml
.common-header
  %h1
    //部分テンプレートのヘッダー
    = link_to root_path do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'

app/views/shared/main_header.html.haml
.header
  .upper-row
    = link_to '#' do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari", class: 'mercari-icon'
    //ログイン時
    .upper-row__user
      .user-information
        = link_to '#' do
          = fa_icon 'bell', class: 'icon'
      .user-information
        = link_to '#' do 
          = fa_icon 'check', class: 'icon'
      .user-information
        = link_to '#', class: 'userpage-link' do
          = image_tag 'mrkr-icon.png', class: 'user-icon', size: '32x32'
    //未ログイン
    -# .upper-row__user
    -#   = link_to '新規会員', '#',class: "upper-row__user__registration" 
      
    -#   = link_to 'ログイン', '#',class: "upper-row__user__login"
    
  .center-row__search
    %form
      %input.center-row__search--input{name: "search", placeholder: "何をお探しですか？", type: "search", style: "width: 100%; height: 40px;"}
      %button.center-row__search--button{title: "検索", type: "submit" }
        = fa_icon 'search'
  %nav.under-row
    = link_to '#', class: "under-row__list" do
      = fa_icon 'list'
      %span
        カテゴリーから探す
    = link_to '#', class: "under-row__list" do
      = fa_icon 'tag'
      %span
        ブランドから探す

// 横に広がった時のヘッダー
.header-wide
  .header-wide__inner
    .upper-row
      .mercari-logo
        = link_to '#' do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari"
      %form.upper-row__search
        %input.upper-row__search--input{name: "search", placeholder: "何かお探しですか？", type: "search", style: "width: 100%; height: 40px;"}
        %button.upper-row__search--button{title: "検索", type: "submit" }
          = fa_icon 'search'
    .under-row
      .under-row__links
        .under-row__links__content
          = link_to '#' do
            = fa_icon 'list'
            %span
              カテゴリーから探す
        .under-row__links__content
          = link_to '#' do
            = fa_icon 'tag'
            %span
              ブランドから探す
      
      %ul.under-row__lists
        %li.list
          = link_to '#' do
            = fa_icon 'heart', class: 'icon'
            いいね！一覧
        %li.list
          = link_to '#' do
            = fa_icon 'bell', class: 'icon'
            お知らせ
        %li.list
          = link_to '#' do 
            = fa_icon 'check', class: 'icon'
            やることリスト
        %li.list
          = link_to '#' do
            = image_tag 'mrkr-icon.png'
            マイページ
      // 未ログイン時
      -# .under-row__user
      -#   .under-row__user__registration
      -#     = link_to '#' do
      -#       新規会員登録
      -#   .under-row__user__login    
      -#     = link_to '#' do
      -#       ログイン