config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #仮のルーティング
  root 'items#index'
  resources :items do
    collection{ get "search"}
    collection do
      get 'items/get_category_children', defaults: { format: 'json' }
      get 'items/get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
  end

  resources :signup, only: [:crate] do
    collection do
      get  'index'
      get  'registration'
      get  'registration_omniauth'
      get  'phone'
      post 'phone' => 'signup#send_sms'
      get  'phone2'
      post 'phone2' => 'signup#check_sms'
      get  'address'
      get  'payment'
      post 'create'
      get  'complete'
    end
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :users, only: [:show, :edit] do
    collection do
      get 'login', to: 'users#login'
      get 'logout', to: 'users#logout'
      get 'card', to: 'users#card'
      get 'exhibiting', to: 'users#exhibiting'
    end
  end
  resources :personals

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  # 購入者と出品者を分けるアソシエーション
  belongs_to :saler, class_name: "User"
  belongs_to :buyer, class_name: "User"

  belongs_to :prefecture
  belongs_to :category
  has_many :photos, dependent: :destroy

  validates_associated :prefecture, :category, :photos

  # 画像と同時に投稿するための記述
  accepts_nested_attributes_for :photos, allow_destroy: true

  # バリデーションの記述
  validates :photos, presence: true

  validates :name, presence: true,length: { maximum: 40 }

  validates :description, length: { maximum: 1000 } ,presence: true

  validates :category, presence: true

  validates :status, presence: true

  validates :shipping_charge, presence: true

  validates :prefecture, presence: true

  validates :days_before_shipment, presence: true

  validates :price,numericality:{ greater_than: 299, less_than: 10000000}, presence: true

  enum prefecture: {

    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,岐阜県:20,静岡県:21,愛知県:22,三重県:23,滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,徳島県:35,香川県:36,愛媛県:37,高知県:38,福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45,沖縄県:46

  }

    scope :be_sold, -> { where.not(buyer_id: nil) }

    scope :be_bought, -> (user_id) { where("buyer_id = ?", user_id) }

    scope :be_indexed, ->{ where.not(status: :stopped).where.not(status: :received) }


  
  def previous
    Item.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    Item.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_search
  before_action :authenticate_user!,except: [:index,:search,:show]

  
  def index
    #テストで用いた記述
    @items = Item.all.order("id DESC").limit(10)
    #カテゴリーごとに並べる
    @ladies = Item.includes(:photos).where(category_id: 0..199).order("updated_at DESC").limit(10)
    @mens = Item.includes(:photos).where(category_id: 200..345).order("updated_at DESC").limit(10)
    @phones = Item.includes(:photos).where(category_id: 898..983).order("updated_at DESC").limit(10)
    @toys = Item.includes(:photos).where(category_id: 685..797).order("updated_at DESC").limit(10)
    #ブランドごとに並べる
    @chanels = Item.includes(:photos).where(brand: "シャネル").order("updated_at DESC").limit(10)
    @vitons = Item.includes(:photos).where(brand: "ルイヴィトン").order("updated_at DESC").limit(10)
    @supremes = Item.includes(:photos).where(brand: "シュプリーム").order("updated_at DESC").limit(10)
    @nikes = Item.includes(:photos).where(brand: "ナイキ").order("updated_at DESC").limit(10)
  end

  def search
    @q = Item.includes(:photos).ransack(search_params)
    @items = @q.result(distinct: true).page(params[:page]).per(10).limit(20)
    @itemsall = Item.all.order("updated_at DESC").limit(20)
  end

  # 商品購入確認画面
  def confirmation
    @item = Item.find(params[:id])
    @address = Address.find_by(user_id: current_user.id)
    card = Card.where(user_id: current_user.id).first
    if card.present?
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    # else
    # # 支払い登録していない場合はマイページの支払い方法登録画面に遷移。
    #   redirect_to card_users_path, notice: "購入に進むには支払い方法の登録が必要です。画面より登録をしてください。"
    end
  end

  # 商品詳細画面
  def show
    @item = Item.find(params[:id])
    @user = User.find_by(id: @item.saler_id)
    @user_items = Item.where(saler_id: @user.id).order("id DESC").limit(6)
    @category_items = Item.where(category_id: @item.category.id).order("id DESC").limit(6)
  end

  def new
    @item = Item.new
    6.times{@item.photos.build}
    
    @parents = Category.where(ancestry: nil)
  end

  def create

    @item = Item.create(item_params)

    if @item.save
      redirect_to root_path, notice: '出品が完了しました'
    else
      @parents = Category.where(ancestry: nil)
      session[:error] = @item.errors.full_messages
      redirect_to new_item_path
    end
  end


  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
  
  def edit
    @item = Item.find(params[:id])
    num = @item.photos.length
    num = 6 - num
    num.times{@item.photos.build}
    
    # 最上層のカテゴリーを取得
    @parents = Category.where(ancestry: nil)
    # 編集する商品の最上層カテゴリーを指定
    @root = @item.category.root_id
    # 編集する商品の中層カテゴリーを指定
    @children = Category.find(@root.to_s).children
    # 編集する商品の最下層カテゴリーを指定
    @grandchildren = Category.find(@item.category.parent_id).children
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)

    if @item.save
      redirect_to root_path, notice: '更新が完了しました'
    else
      @parents = Category.where(ancestry: nil)
      session[:error] = @item.errors.full_messages
      redirect_to edit_item_path
    end
  end


  # 子カテゴリーidを取得するためのアクション
  def get_category_children

    @children = Category.find(params[:parent_id]).children
    respond_to do |format|
      format.html
      format.json { render 'new', json: @children }
    end
  end

  # 孫カテゴリーidを取得するためのアクション
  def get_category_grandchildren
    @grandchildren = Category.find(params[:child_id]).children
    respond_to do |format|
      format.html
      format.json { render 'new', json: @grandchildren}
    end
  end

  # 商品購入の為のpayjpに決済情報とトークンを送る際の定義を記述
  def buy
    @item = Item.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    charge = Payjp::Charge.create(
    amount: @item.price,
    card: params['payjp-token'],
    currency: 'jpy'
    )
    redirect_to action: :done
  end

  # 商品購入完了画面
  def done
    @item_buyer = Item.find(params[:id])
    @item_buyer.update(buyer_id: current_user.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :category_id, :size, :status, :brand, :shipping_charge, :shipping_method, :prefecture_id, :days_before_shipment, :price, photos_attributes: [:id, :photo, :_destroy]).merge(saler_id: current_user.id)
  end
  
  def set_search
    @q = Item.search(params[:q])
  end

  def search_params
    params.require(:q).permit(:name_cont)
  end
end

app/views/items/confirmation.html.haml
.common-container
  %header.common-header
    = render "shared/signup-header"
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-single-head
        購入内容の確認
      %section.buy-content.buy-item
        .buy-content-inner
          %h3.buy-item-image
            = image_tag @item.photos.first.photo, class: "lazyloaded",style: "width: 80px; height: 80px;"
          %p.buy-item-name.bold
            = @item.name
          %form{action: "", method: "POST", novalidate: "novalidate"}
            %p.buy-price-ja.bold
              ¥
              = @item.price
              %span.item-shipping-fee.f14.bold
                送料込み
            %ul.buy-accordion.not-have
              //ポイントがある場合とない場合で分ける
              %li.accordion-parent
                .accordion-toggle
                  ポイントはありません
            %ul.buy-price-table
              %li.buy-price-row.buy-you-pay.bold
                .buy-price-cell
                  支払い金額
                .buy-price-cell
                  %span{"data-buy-pay" => "10000"}
                    ¥
                    = @item.price
            %br
          - if @default_card_information.present?
            -# %button{type: "submit", class: "btn-default btn-red bold"}
            -#   購入する
            = form_tag(action: :buy, method: :post) do
              %script.payjp-button{src: "https://checkout.pay.jp/" ,type: "text/javascript" , "data-key": ENV["PAYJP_KEY"] ,"data-text": "購入する"}

          - else
            %p.has-error-text
              配送先と支払い方法の入力を完了してください。
            %button{type: "submit", class: "btn-default btn-red bold", disabled: "disabled"}
              購入する
      %section.buy-content.buy-user-info
        .buy-content-inner
          %h3
            配送先
          %address.buy-user-info-text
            = "〒" + @address.postcode
            %br
            = @address.prefecture.name
            = @address.city
            = @address.address
            = @address.building
            %br
            = current_user.personal.last_name
            = current_user.personal.first_name
          %p.buy-user-info-text
          %a.buy-user-info-fix
            %span
              変更する
            = fa_icon "chevron-right"
      %section.buy-content.buy-user-info{"data-buy" => "pay-method"}
        .buy-content-inner
          %h3
            支払い方法
          - if @default_card_information
            %p.buy-user-info-text
              = "**** **** **** " + @default_card_information.last4
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              有効期限
              = exp_month + " / " + exp_year
            -# 余裕があればカードブランドのロゴを入れたい部分
            %figure
              %img{src:"//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?465897195", width:"49", height:"20"}
          - else
            %p.buy-user-info-text
              = "/"
          %p
          =link_to card_path(id: current_user.id),class: "buy-user-info-fix" do
            %span
              変更する
            = fa_icon "chevron-right"
    //フッターの部分テンプレート
  = render 'shared/signup-footer'

app/views/items/done.html.haml
.common-container
  .common-header
    %h1
      //会員登録完了画面のヘッダー
      = link_to root_path do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4194600336", alt: "merucari",class: 'common-header__image'
  %main.step5-main
    %section.l-step5-container
      %h2.l-chapter-head.registraition
        商品購入完了
      .l-step5-inner.registration-form
        .l-step5-content
          %p 
            ありがとうございます。
            %br 
            購入が完了しました。
          =link_to root_path(), class: "btn-default btn-red" do
            .start-btn メルカリに戻る
      = link_to "#" do
        %img{class:"step5-banner-sp",src:"//www-mercari-jp.akamaized.net/assets/img/signup/jp/banner-sp.jpg?2651893653"}
      = link_to "#" do
        %img{class:"step5-banner-pc",src:"//www-mercari-jp.akamaized.net/assets/img/signup/jp/banner-pc.jpg?2651893653"}
  = render "shared/signup-footer"

app/views/items/edit.html.haml
.exhibit-screen
  = render partial: 'shared/signup-header'

  - if session[:error].present?
    %ul.has-error-text
      - session[:error].each do |e|
        %li= e
    = session[:error] = nil
  
  .exhibit-content
    
    .exhibit-content__title
      商品の情報を入力
    = render 'form', { item: @item}
    
    = link_to root_path do
      .exhibit-bottom_return.btn-default.btn-gray
        もどる
  
  
  = render partial: 'shared/signup-footer'

app/views/items/show.html.haml
= render partial: 'shared/main_header'
- unless @user.id != current_user.id
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      -# config/breadcrumbs.rbに定義したitems_nameを呼び出し
      - breadcrumb :items_name2
      -# 下記を記述した箇所にパンくずリストを表示させる。
      -# separatorはパンくずの間の区切り「&rsaquo」は出力されると「›」になる。
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"

.information-item
  .information-item_content
    .information-item_content__title
      = @item.name

    .information-item_content__detail
      .information-item_content__detail--image
        .information-item_content-image
          = image_tag @item.photos.first.photo, style: "width: 300px; height: 250px;"

          - unless @item.buyer_id.nil?
            .item-sold-out-badge
              .soldout SOLD
          .item-images
            - @item.photos.each do |photo|
              = image_tag photo.photo
        .information-item_content-image2
          = image_tag @item.photos.first.photo, style: "width: 300px; height: 330px;"
          - unless @item.buyer_id.nil?
            .item-sold-out-badge
              .soldout SOLD
      .information-item_content__detail--price
        .information-item_content-money
          ¥
        .information-item_content-price
          = @item.price
        .information-item_content-detail
          .zeikomi_chara
            (税込)
        .information-item_content-detail2
          送料込み
      
      - if user_signed_in?
        - unless @user.id == current_user.id
          - unless @item.buyer_id.nil?
            .item-buy-btn-desabled-small
              売り切れました
      - else
        - unless @item.buyer_id.nil?
          .item-buy-btn-desabled-small
            売り切れました

      .information-item_content__detail--exhibit
        .information-detail_first-row
          .information-detail_first-row__title
            出品者
          .information-detail_first-row__seller
            .information-detail_first-row__seller--name
              = @user.nickname
            .information-detail_first-row__seller--like
              .seller-like_good
                = fa_icon 'fa-smile-o', class: 'fa-smile-o'
                .seller-like_good__number
                  400
              .seller-like_common
                = fa_icon 'fa-meh-o', class: 'fa-meh-o'
                .seller-like_common__number
                  200
              .seller-like_bad
                = fa_icon 'fa-frown-o', class: 'fa-frown-o'
                .seller-like_bad__number
                  100
        
        .information-detail_second-row
          .information-detail_second-row__title
            カテゴリー
          .information-detail_second-row__category
            .information-detail_second-row__category--1
              = @item.category.root.name
            .information-detail_second-row__category--2
              >
              = @item.category.parent.name
            .information-detail_second-row__category--3
              >
              = @item.category.name
        
        .information-detail_third-row
          .information-detail_third-row__title
            ブランド
          .information-detail_third-row__brand
            - unless @item.brand.nil?
              = @item.brand
            - else
              %p -
              
            
        
        .information-detail_fourth-row
          .information-detail_fourth-row__title
            商品のサイズ
          .information-detail_fourth-row__size
            = @item.size
        
        .information-detail_fifth-row
          .information-detail_fifth-row__title
            商品の状態
          .information-detail_fifth-row__status
            = @item.status
        
        .information-detail_sixth-row
          .information-detail_sixth-row__title
            配送料の負担
          .information-detail_sixth-row__shipping_charge
            = @item.shipping_charge
        
        .information-detail_seventh-row
          .information-detail_seventh-row__title
            配送の方法
          .information-detail_seventh-row__method
            = @item.shipping_method
        
        .information-detail_eighth-row
          .information-detail_eighth-row__title
            発送元地域
          .information-detail_eighth-row__prefecture
            都道府県情報
        
        .information-detail_ninth-row
          .information-detail_ninth-row__title
            発送日の目安
          .information-detail_ninth-row__day
            = @item.days_before_shipment
      
      .information-item_content__detail--price
        .information-item_content-money
          ¥
        .information-item_content-price
          = @item.price
        .information-item_content-detail
          .zeikomi_chara
            (税込)
        .information-item_content-detail2
          送料込み
    
    .information-item_content__value
      .information-item_content-money
        ¥
      .information-item_content__value--price
        = @item.price
      .information-item_content__value--detail
        .zeikomi_chara
          (税込)
      .information-item_content__value--detail2
        送料込み

    - if user_signed_in?
      - unless @user.id == current_user.id
        - if @item.buyer_id.nil?
          = link_to confirmation_item_path do
            .information-item_content__purchace
              購入画面に進む
        - else
          .item-buy-btn-desabled
            売り切れました
    - else
      - if @item.buyer_id.nil?
        = link_to confirmation_item_path do
          .information-item_content__purchace
            購入画面に進む
      - else
        .item-buy-btn-desabled
          売り切れました
    
    .information-item_content__description
      = @item.description
    
    - unless @user.id == current_user.id
      .information-item_content__bottom
        .information-item_content__bottom--like
          .information-item_heart-icon
            = fa_icon 'heart', class: 'fa-heart'
          .information-item_like
            いいね！
          .information-item_like-number
            10
        .information-item_content__bottom--report
          .information-item_flag-icon
            = fa_icon 'flag', class: 'fa-flag'
          .information-item_report
            不適切な商品の報告
        .information-item_content__bottom--safe
          .information-item_lock-icon
            = fa_icon 'lock', class: 'fa_lock'
          .information-item_safe
            あんしん・あんぜんへの取り組み
    
      .safe_effort
        .information-item_lock-icon
          = fa_icon 'lock', class: 'fa_lock'
        .information-item_safe
          あんしん・あんぜんへの取り組み
  
  - unless @user.id != current_user.id
    .exhibit_edit-and-delete_box
      = link_to edit_item_path(@item.id) do
        .exhibit_edit-and-delete_box__edit
          商品の編集
      .exhibit_edit-and-delete_box__or
        or
      .exhibit_edit-and-delete_box__stop
        出品を一旦停止する
      = link_to item_path(@item.id), method: :delete, data: { confirm: "本当に削除しますか？" } do
        .exhibit_edit-and-delete_box__delete
          この商品を削除する

  .information-item_comment
    .information-item_comment__content
      .information-item_comment__content--left
        = link_to '#' do
          .information-item_user-icon
            icon画像
      .information-item_comment__content--right
        .information-item_user-name
          = @user.nickname
        .information-item_user-comment
          .information-item_user-comment__content
            コメント内容
          .information-item_user-comment__bottom
            .information-item_user-comment__bottom--days
              = fa_icon 'clock', class: 'fa-clock-o'
              .information-item_clock-right
                300日前
            = fa_icon 'flag', class: 'fa-flag'

    
    .information-item_comment__note
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    
    - unless @item.buyer_id.nil?
      %form.information-item_comment__input
        %textarea.information-item_comment__input--text{type: "text", style: "width: 710px; height: 120px;"}
        %input.information-item_comment__input--send{type: "submit", value: "売り切れのためコメントできません", style: "width: 710px; height: 50px;", disabled: "disabled"}

      %form.information-item_comment__input2
        %textarea.information-item_comment__input2--text{type: "text", style: "width: 90vw; height: 120px;"}
        %input.information-item_comment__input2--send{type: "submit", value: "売り切れのためコメントできません", style: "width: 90vw; height: 50px;", disabled: "disabled"}

    - else
      %form.information-item_comment__input
        %textarea.information-item_comment__input--text{type: "text", style: "width: 710px; height: 120px;"}
        %input.information-item_comment__input--send{type: "submit", value: "コメントする", style: "width: 710px; height: 50px;"}

      %form.information-item_comment__input2
        %textarea.information-item_comment__input2--text{type: "text", style: "width: 90vw; height: 120px;"}
        %input.information-item_comment__input2--send{type: "submit", value: "コメントする", style: "width: 90vw; height: 50px;"}

  .information-item_link
    .information-item_link__back
      = link_to item_path(@item.previous) do
        .information-item_link__back--icon
          <
        .information-item_link__back--name
          = @item.previous.name
    .information-item_link__after
      - if @item.next.nil?
        -
      - else
        = link_to item_path(@item.next) do
          .information-item_link__after--name
            = @item.next.name
          .information-item_link__after--icon
            >

  .information-item_share-box
    .information-item_share
      //共有の仕方を調べる
      .information-item_share__facebook
        = fa_icon 'facebook-square', class: 'fa-facebook-square'
      .information-item_share__twitter
        = fa_icon 'twitter-square', class: 'fa-twitter-square'
      .information-item_share__pinterest
        = fa_icon 'pinterest-square', class: 'fa-pinterest-square'

  
  .information-item_other-item
    = link_to '#' do
      .information-item_other-item__name
        = @user.nickname
        のその他出品
    .information-item_other-item__content
      - @user_items.each do |user_item|
        = link_to item_path(user_item) do
          .other-item_list
            .other-item_list__image
              = image_tag user_item.photos.first.photo, style: "width: 230px; height:230px;"
            %h6.other-item_list__name
              = user_item.name
            .other-item_list__value
              .other-item_list__value--price
                ¥
                = user_item.price
              .other-item_list__value--heart
                = fa_icon 'fa-heart-o', class: 'fa-heart-o'
                .heart-number
                  18
    
    .information-item_other-item__content2
      - @user_items.each do |user_item|
        = link_to item_path(user_item) do
          .other-item_list
            .information-item_sample-box
              .information-item_sample-box__image
                = image_tag user_item.photos.first.photo, style: "width: 100%; height:100%;"
              .information-item_sample-box__price
                ¥
                = user_item.price

  
  .information-item_other-item
    = link_to '#' do
      .information-item_other-item__name
        = @item.category.name
        その他の商品
    .information-item_other-item__content
      - @category_items.each do |category_item|
        = link_to item_path(category_item) do
          .other-item_list
            .other-item_list__image
              = image_tag category_item.photos.first.photo, style: "width: 230px; height: 230px;"
            %h6.other-item_list__name
              = category_item.name
            .other-item_list__value
              .other-item_list__value--price
                ¥
                = category_item.price
              .other-item_list__value--heart
                = fa_icon 'fa-heart-o', class: 'fa-heart-o'
                .heart-number
                  18


    .information-item_other-item__content2
      .other-item_list
        - @category_items.each do |category_item|
          = link_to item_path(category_item) do
            .information-item_sample-box
              .information-item_sample-box__image{src: "#{category_item.photos.first.photo}", style: "width: 100%; height:100%;"}
                = image_tag category_item.photos.first.photo, style: "width: 100%; height:100%;"
              .information-item_sample-box__price
                ¥
                = category_item.price

- unless @user.id != current_user.id
  %nav.bread-crumbs
    // パンくずリスト
    .bread-crumbs__line
      -# config/breadcrumbs.rbに定義したitems_nameを呼び出し
      - breadcrumb :items_name
      -# 下記を記述した箇所にパンくずリストを表示させる。
      -# separatorはパンくずの間の区切り「&rsaquo」は出力されると「›」になる。
      = breadcrumbs separator: " &rsaquo; ", class:"bread-crumbs-list"


= render partial: 'shared/main_aside'

= render partial: 'shared/main_footer'


- if user_signed_in?
  - unless @user.id == current_user.id
    - if @item.buyer_id.nil?
      .exhibit-footer_fixed
        = link_to confirmation_item_path do
          .exhibit-footer_fixed__purchace
            購入画面に進む
- else
  .exhibit-footer_fixed
    = link_to confirmation_item_path do
      .exhibit-footer_fixed__purchace
        購入画面に進む